credentials:
  usernames:
    test:
      name: test
      password: $2b$12$IduJyao8woXr545errWM8ux9CDFPcDIv4bPpdVuGD2PMYpHXAlhPO

cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name